title: "Victor Glowinski"
logo: img/bachelorvictor
description: "Portfolio Informaticien de Gestion - Bachelor of Science de la Haute Ecole de Gestion Gen√®ve en Informatique de Gestion"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
